server:
  port: 8899

spring:
  profiles:
    active: local
    include: private
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger 3.0 오류 해결

  redis:
    host: localhost
    port: 6379

swagger:
  enable: true