spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saver_db?validationQuery="select 1"&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual

logging.level:
  org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL을 남긴다.
  org.hibernate.type: trace # SQL 실행 파라미터를 로그로 남긴다.

swagger:
  enable: true

location:
  root: resources
  image-dir: /images

